name: Build and Release Application

on:
  push:
    branches:
      - main  # Only run on the main branch
    tags:
      - 'v*'  # Only trigger on tags like v1.0, v2.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller kali_mc.spec  # Use your .spec file

      - name: Create ZIP file for release
        run: |
          cd dist
          zip -r kali_mc.zip kali_mc/  # Adjust the output folder name based on your spec

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: kali_mc_build
          path: dist/kali_mc.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: kali_mc_build

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "kali_mc.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
